from django.utils.translation import gettext_lazy as _

v_company = 'company'
vp_company = 'companies'

since = _('since')
icb = _('industry classification benchmark')
market = _("market")
purpose = _("purpose")
secretary = _("secretary")
settle_internal = _("internal rules of the board")
turnover = _('turn over')
capital_socnomtotal = _('capital social nominal total')
capitalisation = _('capitalisation')
net_profit = _('net profit')
net_profit_help = _("En million d'euros")
total_dividend = _('dividende total')
total_dividend_help = _("En million d'euros")
dividend = _('dividend')
securities = _('securities')
current = _('current')

duration_mandate = _("duration mandate")
matrix_skills = _("matrix skills")
instance_comex = _("governing is comex")
age_limit_pdg = _("pdg age limit")
age_limit_dg  = _("dg age limit")
stock_min_status = _("company status minimum stock")
stock_min_rule = _("council rules minimum stock")
share_capital = _("share capital")

results = _('%s companies found')
result = _('%s company found')
page = _('for %s page')
pages = _('for %s pages')

search = _('search')
search_placeholder = _('siren, company...')
toomuch = _('In view of the high number of results (% s) we advise you to search by SIREN')
countries = _('countries')

fr_ape = _('core business') #_("secteur d'activités")
fr_ape_null = _('APE code not specified')
fr_ape_noun = _("ape noun")
fr_legalform = _('legal form')
fr_legalform_null = _('legal form not specified')
fr_category = _("category")
fr_slice_effective = _("slice effective")
fr_effective = _("effective")

fr_date_rcs = _("date rcs")
fr_siret = _("siret")
fr_isin = _("isin")
fr_ticker = _("ticker")
fr_coderef = _("code reference")
fr_index = _("Paris index")
fr_governance = _('governance')
fr_evaluation = _('evaluation')
fr_quality_independent = _('quality independent')
fr_secretary = _('secretary')